# ===============
# ACTION MARKDOWN
# ===============

name: Action-Markdown

# Activation Events
# =================

on:
  # When the action.yaml file changes
  push:
    paths:
      - action.yaml

  # Manual workflow dispatch
  workflow_dispatch:

# Jobs
# ====

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository ✅
      # ======================

      - name: checkout
        uses: actions/checkout@v3

      # Generate Action Markdown Outputs 📜
      # ===================================

      - name: generate action markdown
        id: action-md
        uses: Shresht7/action-markdown@main

      # Markdown Slots 📋
      # =================

      - name: update readme slots
        id: markdown-slots
        uses: Shresht7/markdown-slots@main
        with:
          slots: |
            inputs: ${{ steps.action-md.outputs.inputs-md-table }}
            outputs: ${{ steps.action-md.outputs.outputs-md-table }}

      # Push Changes 🌎
      # ===============

      - name: update readme
        id: update-action-readme
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "update-action-readme"
          commit-message: "Update README 📄"
          title: "Update README 📄"
