# =============
# ACTION README
# =============

name: Action-Readme

# Activation Events
# =================

on:
  # When the action.yaml file changes
  push:
    paths:
      - action.yaml

  # Manual workflow dispatch
  workflow_dispatch:

# Jobs
# ====

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository ✅
      # ======================

      - name: checkout
        uses: actions/checkout@v3

      # Generate Action Markdown Outputs 📜
      # ===================================

      - name: generate action markdown
        id: action-md
        uses: Shresht7/action-markdown@main

      # Markdown Slots 📋
      # =================

      - name: update readme slots
        id: markdown-slots
        uses: Shresht7/markdown-slots@main
        with:
          slots: |
            description: ${{ fromJSON(steps.action-md.outputs.metadata).description }}
            inputs: ${{ steps.action-md.outputs.inputs-md-table }}
            outputs: ${{ steps.action-md.outputs.outputs-md-table }}

      # Push Changes 🌎
      # ===============

      - name: check for changes
        id: git-diff
        run: |
          if git diff --exit-code; then
            echo "::set-output name=changes_exist::false"
          else
            echo "::set-output name=changes_exist::true"
          fi

      - name: commit and push
        if: ${{ steps.git-diff.outputs.changes_exist == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update README.md 📄'
          git push
